### PR TITLE
Create basic form page

### PR DESCRIPTION
**Pull request by om840**

### CODE REVIEW

**Comment by mepda** [comment]
Thanks for making a Pull Request -- This repo is meant to show Nuxt examples. What you submitted was just an HTML webpage.
If you could put this as a Vue component and then import it into a Vue page I'll accept it.

**Comment by om840** [comment]
sir same code without any changes ??

**Comment by mepda** [comment]
You'd need to modify the code you submitted so it's broken down into a "component" and a "page". See "components -> Resources.vue" and "pages -> index.vue" for an example of how this works.

**Comment by om840** [comment]
ok sir thank you

**Pull request closed without merging**
